#!/bin/bash

#btred -I  ../../parsing_czech/format-conversions/pdt_formats/pml2pls.btred pml/*/*.[at].gz

cd pml

for dir1 in *; do
	cd $dir1

	for f1 in *.[at].gz; do
		btred -I  ../../parsing_czech/format-conversions/pdt_formats/pml2pls.btred $f1
	done

	cd ..
done

cd..

