#!/bin/bash

echo "*****************************start date****************************"
date
echo "*****************************start date****************************"


sh clear_tmp

sh prepare_sources

cd txt_src

for d in *; do 

#/tmp/czsem/parsing_czech/machine-annotation/run_all $d/out $d/*.txt
cd $d
../../../../parsing_czech/PDT/tools/machine-annotation/run_all out '*.txt'
../../../../parsing_czech/t-analysis/run out/5-pml
cd ..


mkdir ../pml/$d
mv $d/out/5-pml/*.[wmat].gz ../pml/$d

done 

cd ..
sh make_pls
sh make_tpls_list

sh convert2fs.sh


cd pml

for fs in *; do
mkdir ../../../netgraph/corpus/hasici/$fs
mv $fs/*.t.gz.fs ../../../netgraph/corpus/hasici/$fs
done 



#ja to spustit na pozadi:
#echo './parse > parse_log 2>&1 &!' | zsh

echo "*****************************end date****************************"
date
echo "*****************************end date****************************"
