#!/bin/bash

echo "*****************************start date****************************"
date
echo "*****************************start date****************************"


sh clear_tmp

sh prepare_sources

cd txt_src

for d in *; do 

#/tmp/czsem/parsing_czech/machine-annotation/run_all $d/out $d/*.txt
../../../parsing_czech/PDT/tools/machine-annotation/run_all $d/out $d/*.txt
../../../parsing_czech/t-analysis/run $d/out/5-pml


mkdir ../pml/$d
mv $d/out/5-pml/*.[wmat].gz ../pml/$d

done 

cd ..
sh make_pls


#ja to spustit na pozadi:
#echo './parse > parse_log 2>&1 &!' | zsh

echo "*****************************end date****************************"
date
echo "*****************************end date****************************"
