#!/bin/bash

 mkdir txt_src

cd html_src
 
for dir1 in *; do
	
	mkdir ../txt_src/$dir1
	
	cd $dir1

	for f in *; do
#	 	sed -n -e 's/\(<P>.*<\/P>\).*$/\1/p' < $f > short_$f.htm

sed \
-e 's/<[Pp][^>]*>/\n/' \
-e 's/&#188;/čtvrtina/' \
-e 's/&amp;/\&/' \
-e 's/&nbsp;/ /' \
-e 's/&nbsp;/ /' \
-e 's/&nbsp;/ /' \
-e 's/&nbsp;/ /' \
-e 's/&nbsp;/ /' \
-e 's/&nbsp;/ /' \
-e 's/&nbsp;/ /' \
-e 's/&nbsp;/ /' \
-e 's/&nbsp;/ /' \
-e 's/<img[^>]*>//' \
-e 's/<img[^>]*>//' \
-e 's/<img[^>]*>//' \
-e 's/<img[^>]*>//' \
-e 's/<img[^>]*>//' \
-e 's/<[^>]*>//' \
-e 's/<[^>]*>//' \
-e 's/<[^>]*>//' \
-e 's/<[^>]*>//' \
-e 's/<[^>]*>//' \
-e 's/<[^>]*>//' \
-e 's/<[^>]*>//' \
-e 's/<[^>]*>//' \
-e 's/<[^>]*>//' \
-e 's/<[^>]*>//' \
-e 's/<[^>]*>//' \
-e 's/<[^>]*>//' \
-e 's/<[^>]*>//' \
-e 's/<[^>]*>//' \
-e 's/<[^>]*>//' \
-e 's/<[^>]*>//' \
-e 's/<[^>]*>//' \
< $f > ../../txt_src/$dir1/$f.txt

	rename .htm '' ../../txt_src/$dir1/$f.txt


	done
	
	cd ..

done
 




# < isol2_short_article.php\?id\=48194.htm 
