#!/bin/bash


cd html_src
 
for dir1 in *.isol2; do
	
	mkdir ../txt_src/$dir1
	
	cd $dir1

	for f in *; do

sed -n \
-e 's/&#188;/ètvrtina/g' \
-e 's/&amp;/\&/g' \
-e 's/&nbsp;/ /g' \
-e 's/<img[^>]*>//g' \
-e 's/<[^Pp>]*>//g' \
-e 's/\([0-9]\):\([0-9][[0-9]\)/\1.\2/g' \
-e 's/<[Pp][^>]*>\([^< ][^<]*\)[^>]*>/\.\n\1/gp' \
< $f > ../../txt_src/$dir1/$f.txt

#	rename .htm '' ../../txt_src/$dir1/$f.txt
#-e 's/^.*[^0-9]\([0-9]*[0-9]\):\([0-9][0-9]\).*$/\1.\2/g' \
#-e 's/^\([0-9]*[0-9]\):\([0-9][0-9]\).*$/\1.\2/g' \


	done
	
	cd ..

done
 




# < isol2_short_article.php\?id\=48194.htm 
