#! /bin/bash

if [ -z $2 ] ; then
	echo "Usage: $0 dirname rulefile" >&2
	exit
fi

echo -e "Converting..." >&2
$A2T/2/macros/totbl $1/*.t1.pls.gz

echo -e "\nTransforming..." >&2
for f1 in $1/*.2i.tbl; do
	f=${f1/.2i.tbl/}
	echo $f >&2
	$A2T/2/apply $f1 $2 2>&1 > $f.2o.tbl | sed 's/^.*\ch//g'
done

echo -e "\nMerging..." >&2
$A2T/2/macros/merg $1/*.t1.pls.gz > /dev/null
rm -f $1/*.t2.*~

#../compare $1 t\#.pls.gz t2.pls.gz

