#! /bin/bash

if [ -z $2 ] ; then
	echo "Usage: $0 dirname rulefile" >&2
	exit
fi

echo -e "Converting..." >&2
$A2T/4/macros/totbl $1/*.t3.pls.gz

echo -e "\nTransforming..." >&2
for f1 in $1/*.4i.tbl; do
	f=${f1/.4i.tbl/}
	echo $f >&2
	$FNTBL/exec/most_likely_tag.prl -l $A2T/4/train/T-lem0.lex -t '---','---' $f1 |\
	$FNTBL/exec/most_likely_tag.prl -l $A2T/4/train/T-type.lex -t '---','---' - |\
	$FNTBL/exec/most_likely_tag.prl -l $A2T/4/train/T-sem.lex -t '---','---' - |\
	$FNTBL/exec/most_likely_tag.prl -l $A2T/4/train/T-subf.lex -t '---','---' - > $f1.lex
	$A2T/4/apply $f1.lex $2 2>&1 > $f.4o.tbl | sed 's/^.*\ch//g'
done

echo -e "\nMerging..." >&2
$A2T/4/macros/merg $1/*.t3.pls.gz > /dev/null
rm -f $1/*.t4.*~

