#! /bin/bash

if [ -z $2 ] ; then
	echo "Usage: $0 dirname rulefile" >&2
	exit
fi

echo -e "Converting..." >&2
$A2T/3/macros/totbl $1/*.t2.pls.gz

echo -e "\nTransforming..." >&2
for f1 in $1/*.3i.tbl; do
	f=${f1/.3i.tbl/}
	echo $f >&2
	$A2T/3/apply $f1 $2 -nonsequential 2>&1 > $f.3o.tbl | sed 's/^.*\ch//g'
done

echo -e "\nMerging..." >&2
$A2T/3/macros/merg $1/*.t2.pls.gz >/dev/null
rm -f $1/*.t3.*~

#../compare $1 t\#.pls.gz t3.pls.gz

